export const SET_CATEGORIES = 'SET_CATEGORIES'
export const POST_CATEGORIES = 'POST_CATEGORIES'
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES'
export const PATCH_CATEGORIES = 'PATCH_CATEGORIES'

export const SET_TOKEN = 'SET_TOKEN'

export const SET_USER = 'SET_USER'
export const SET_LOGIN = 'SET_LOGIN'

export const SET_ACCOUNT = 'SET_ACCOUNT'
export const SET_PASSWORD = 'SET_PASSWORD'

export const SET_PARSER = 'SET_PARSER'
export const SET_URLS = 'SET_URLS'

export const SET_PHOTO = 'SET_PHOTO'

export const SET_IMAGE_FILE = 'SET_IMAGE_FILE'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES'
export const SET_ARTICLE = 'SET_ARTICLE'
export const SET_ARTICLES = 'SET_ARTICLES'
export const DELETE_ARTICLES = 'DELETE_ARTICLES'

export const SET_LOCALE = 'SET_LOCALE'

export const CLEAR_URLSET = 'CLEAR_URLSET'
